version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - rabotaua/frontend
      - rabotaua/backend
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - rabotaua/frontend
      - rabotaua/backend
