version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - rabotaua/frontend
      - rabotaua/backend
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - rabotaua/frontend
      - rabotaua/backend
    groups:
      devDependencies:
        patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'husky'
          - 'jest'
          - 'lint-staged'
          - 'prettier'
          - 'ts-*'
          - 'typescript'
      dependencies:
        patterns:
          - '@actions/*'
