name: "Kubernetes Tools"
description: "GitHub Action To Configure Basic Kubernetes Tools"
inputs:
  kubeconfig:
    description: "kubeconfig file contents"
    required: true
  kubectlVersion:
    description: "kubectl version to install"
    default: "1.22.3"
    required: false
  helmVersion:
    description: "helm version to install"
    default: "3.7.1"
    required: false
  githubUsername:
    description: "github username, if given will be used to login helm to ghcr.io"
    required: false
  githubPassword:
    description: "github password, if given will be used to login helm to ghcr.io"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
